project_name: EasyPeasy
project_shortcut: EP
project_short_description: Imaginary data analysis
project_extended_description: >-
  For performing imaginary calculations based on a theoretical model
  and refining its parameters against experimental data
project_copyright_years: 2021-2026

home_repo_name: peasy
homepage_url: https://easyscience.github.io/peasy

lib_repo_name: peasy-lib
lib_package_name: easypeasy
lib_python_min: '3.11'
lib_python_max: '3.13'
lib_docs_url: https://easyscience.github.io/peasy-lib

app_repo_name: peasy-app
app_docs_url: https://easyscience.github.io/peasy-app
