# Main configuration
project_name: EasyPeasy
project_shortcut: EP
project_short_description: Imaginary data analysis
project_extended_description: >-
  For performing imaginary calculations based on a theoretical model
  and refining its parameters against experimental data
project_copyright_years: 2021-2026
project_contact_email: support@easydiffraction.org

# Project / umbrella repository settings
project_repo_name: peasy
project_homepage_url: https://easyscience.github.io/peasy

# Library settings
lib_repo_name: peasy-lib
lib_package_name: easypeasy
lib_python_min: '3.11'
lib_python_max: '3.13'
lib_doi: 10.5281/zenodo.16806521
lib_docs_url: https://easyscience.github.io/peasy-lib

# Application settings
app_repo_name: peasy-app
app_doi: 10.5281/zenodo.16806521
app_docs_url: https://easyscience.github.io/peasy-app
